DROP TABLE IF EXISTS ejercicio;
DROP TABLE IF EXISTS rutina;

CREATE TABLE ejercicio(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	idRutina INTEGER NOT NULL,
	nombre VARCHAR(100) NOT NULL,
	series integer NOT NULL,
	repeticiones INTEGER NOT NULL,
	FOREIGN KEY (idRutina) REFERENCES rutina(id)
);
CREATE TABLE rutina(
	id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	nombre VARCHAR(100) NOT NULL
);